### ISSUE TITLE
sketchybar disappears after laptop goes to sleep - after last update

### ISSUE THREAD

**Issue by bassamsdata** [FelixKratz/SketchyBar#430]
first and foremost, i want to express my gratitude for creating this fantastic bar. 

Up until a couple of days ago, i had never encountered any problems with sketchybar. however, after the latest update, i noticed that the sketchybar disappears when my laptop goes to sleep, especially when it's left idle for a few hours. 

it doesn't occur consistently, but it happens to me twice a day. this issue only started after the last update. i attempted to resolve it by uninstalling sketchybar and then reinstalling it, but unfortunately, that did not resolve the problem.

sketchybar version: v2.18.0
MacOS version: 12.6 (I'm not sure if it is because the old version but I'm planning to update this week. just I had no storage space in my mac :) )

thank you

**Comment by FelixKratz** [comment]
It is probably because of one of these commits:
* 5a63ad8
* 7305fbc
Which I did to solve #422 I think the first commit can be reverted in its entirety without causing any regression. I will have a look.

**Comment by bassamsdata** [comment]
thank you for your prompt response.

to be honest, when i reviewed the log for the new update, i suspected that the issue might be related to it. i held off on submitting this issue because i initially thought it might be unique to my laptop (though i'm not entirely certain).

> i cannot reproduce this with my setup

 i'm unsure about how i can assist in diagnosing the root cause of the problem. it's possible that the issue may be tied to my older macos version, but i'm planning to update my mac this week.

once again, thank you for your help.

**Comment by FelixKratz** [comment]
You could try the current commit: https://github.com/FelixKratz/SketchyBar/commit/9d9529cb79de62ded7346abfaf2a0bcc6cf70bd2

To do this simply run:
```bash
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
and then to go back to the stable version:
```bash
brew uninstall sketchybar
brew install sketchybar
brew services restart sketchybar
```

**Comment by bassamsdata** [comment]
this is [my config](https://github.com/bassamsdata/myConfig/tree/main), if it helps.

**Comment by bassamsdata** [comment]
> You could try the current commit: https://github.com/FelixKratz/SketchyBar/commit/9d9529cb79de62ded7346abfaf2a0bcc6cf70bd2

Thank you 🙏. I did that now and I'll wait for a day or two to see if the issue persisted or not. then will update here.

**Comment by nbn22385** [comment]
I came to the issues to see if someone reported this, because I just started experiencing it too. 

For me to reproduce consistently:

- close the lid of my Macbook Air for a few seconds (not enough to enter sleep) and reopen it, and the bar is gone. 
- close the lid for over a minute (enough to enter sleep) and reopen it, and the bar is gone.

I tried the updated commit https://github.com/FelixKratz/SketchyBar/commit/9d9529cb79de62ded7346abfaf2a0bcc6cf70bd2 and repeated the steps above and the behavior is different but not perfect:

- close the lid of my Macbook Air for a few seconds (not enough to enter sleep) and reopen it, and the bar is gone. 
- close the lid for over a minute (enough to enter sleep) and reopen it, and the bar reappears correctly.

Hopefully this can shed some light on the issue.

**Comment by bassamsdata** [comment]
thanks for your patience. after three days of testing, i'd like to share my observations.

here's what i did:

```
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
upon completing these steps, sketchybar exhibited instability. it continued to disappear and reappear as if it was undergoing a restart, and this behavior occurred even when the computer was not in sleep mode.

i then tried the following:
```
brew uninstall sketchybar
brew install sketchybar
brew services restart sketchybar
```
following this second set of actions, the issue only occurred once for the remainder of that day. on the second day and half of the third day, it worked perfectly, leading me to believe that the issue was resolved. unfortunately, it resurfaced twice within a couple of hours: once after the computer had been asleep for two hours and again immediately after a 15-minute period of sleep. 

#### **Note**: i want to mention that in order to bring `sketchybar` back and make it reappear, i had to use the command `sketchybar --reload`. 

thanks for your assistance.

**Comment by FelixKratz** [comment]
Could you see if you find the crash logs for sketchybar by going to:
Applications -> Utilities -> Console.app
and in Console.app choose "Crash Reports" in the left hand panel and look for a crash report for sketchybar

**Comment by rijojohn85** [comment]
I have the same issue. Checked the Crash Reports, nothing about sketchybar.
I've tried installing the head version, still the same issue.

No idea why or how it happens.

**Comment by FelixKratz** [comment]
Could you try latests commit with
```bash
brew upgrade sketchybar --fetch-HEAD
```
if you have previous master installed.

**Comment by bassamsdata** [comment]
thank you,
many crash reports but they are more than 3 days ago. I don't have new ones.
here is the last one on 31 October.

I installed last commit. I will see if the issue persists.

<details>
  <summary>crash report</summary>
  
  

  ```report
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               sketchybar [10787]
Path:                  /usr/local/opt/sketchybar/bin/sketchybar
Identifier:            sketchybar
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-31 10:26:37.7842 -0400
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        B945E6FE-3CE4-EB79-12B2-9BAF0A92AB40

Sleep/Wake UUID:       3E4A69A8-68AC-48BC-B31F-373E503E4646

Time Awake Since Boot: 570000 seconds
Time Since Wake:       2170 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000180080020
Exception Codes:       0x0000000000000001, 0x0000000180080020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [10787]

VM Region Info: 0x180080020 is not in any region.  Bytes after previous region: 1671811105  Bytes before following region: 105546673291232
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 111245000-11c623000    [179.9M] r--/rwx SM=COW  ...t_id=c48561b7
--->  GAP OF 0x5ffee39dd000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff807bac293 objc_retain + 35
1   libobjc.A.dylib               	    0x7ff807bb6553 objc_setProperty_atomic + 47
2   sketchybar                    	       0x10a1a8985 __30-[media_context media_change:]_block_invoke_2 + 53
3   MediaRemote                   	    0x7ff81f36c72e __MRMediaRemoteGetNowPlayingInfoForOrigin_block_invoke + 78
4   MediaRemote                   	    0x7ff81f36c530 __MRMediaRemoteGetNowPlayingInfoForPlayer_block_invoke + 64
5   MediaRemote                   	    0x7ff81f36f250 ___MRGetNowPlayingInfo_block_invoke_2 + 48
6   libdispatch.dylib             	    0x7ff807b610cc _dispatch_call_block_and_release + 12
7   libdispatch.dylib             	    0x7ff807b62317 _dispatch_client_callout + 8
8   libdispatch.dylib             	    0x7ff807b6ec78 _dispatch_main_queue_drain + 943
9   libdispatch.dylib             	    0x7ff807b6e8bb _dispatch_main_queue_callback_4CF + 31
10  CoreFoundation                	    0x7ff807e1df37 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                	    0x7ff807ddefcf __CFRunLoopRun + 2771
12  CoreFoundation                	    0x7ff807ddde3c CFRunLoopRunSpecific + 562
13  HIToolbox                     	    0x7ff810a8d5e6 RunCurrentEventLoopInMode + 292
14  HIToolbox                     	    0x7ff810a8d34a ReceiveNextEventCommon + 594
15  HIToolbox                     	    0x7ff810bdd2ea _AcquireNextEvent + 45
16  HIToolbox                     	    0x7ff810bd5f1d RunApplicationEventLoop + 174
17  sketchybar                    	       0x10a182d4e main + 862
18  dyld                          	       0x11119252e start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff807d14f48 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff807d14f48 start_wqthread + 0

Thread 3:: AMCP Logging Spool
0   libsystem_kernel.dylib        	    0x7ff807cdc9b6 semaphore_wait_trap + 10
1   caulk                         	    0x7ff8108192e6 caulk::mach::semaphore::wait_or_error() + 16
2   caulk                         	    0x7ff810801148 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	    0x7ff810800e0c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff807d194e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff807d14f6b thread_start + 15

Thread 4:: CVDisplayLink
0   libsystem_kernel.dylib        	    0x7ff807cdf3ea __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff807d19aa4 _pthread_cond_wait + 1302
2   CoreVideo                     	    0x7ff80f5bce60 CVDisplayLink::waitUntil(unsigned long long) + 370
3   CoreVideo                     	    0x7ff80f5bbddc CVDisplayLink::runIOThread() + 526
4   libsystem_pthread.dylib       	    0x7ff807d194e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff807d14f6b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff807d14f48 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000180080000  rbx: 0x00006000035c8580  rcx: 0x0000000180080000  rdx: 0x0000600003bc3c20
  rdi: 0x0000600003bc3c20  rsi: 0x00007ff82291352d  rbp: 0x00007ff7b5d80930  rsp: 0x00007ff7b5d808f8
   r8: 0x000000000000000b   r9: 0x0000000000000003  r10: 0x000000010a1af312  r11: 0x000000010a1a8a80
  r12: 0x0000000000000000  r13: 0x00007ff807bac400  r14: 0x00007fe6df00a200  r15: 0x0000600003bc4b60
  rip: 0x00007ff807bac293  rfl: 0x0000000000010206  cr2: 0x0000000180080020
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  5f 5d c3 49 8b 46 20 4c-21 f8 48 8b 48 08 48 89  _].I.F L!.H.H.H.
  c8 48 83 e0 fe f6 c1 01-75 1e 8b 40 08 83 c0 07  .H......u..@....
  83 e0 f8 48 01 f0 48 83-f8 11 be 10 00 00 00 48  ...H..H........H
  0f 43 f0 e9 68 ff ff ff-48 8b 00 eb dd 48 85 ff  .C..h...H....H..
  0f 84 83 00 00 00 89 f8-83 e0 01 48 85 c0 75 79  ...........H..uy
  48 8b 07 48 b9 f8 ff ff-ff ff 7f 00 00 48 21 c1  H..H.........H!.
 [48]8b 51 20 f6 c2 04 74-38 a8 01 74 56 48 b9 00  H.Q ...t8..tVH..	<==
  00 00 00 00 00 00 01 48-89 c2 48 c1 ea 37 74 49  .......H..H..7tI
  48 89 c2 48 01 ca 72 12-f0 48 0f b1 17 74 3a a8  H..H..r..H...t:.
  01 75 e4 31 f6 e9 4d fe-01 00 31 f6 e9 4c b0 00  .u.1..M...1..L..
  00 66 83 79 1c 00 79 0e-83 e2 02 48 85 d2 74 06  .f.y..y....H..t.
  f6 41 28 02 75 17 48 8b-35 18 fe 8d 41 ff 25 5a  .A(.u.H.5...A.%Z

Binary Images:
    0x7ff807ba6000 -     0x7ff807bdffff libobjc.A.dylib (*) <4d9b0dca-7151-3875-b98e-b255db8267a8> /usr/lib/libobjc.A.dylib
       0x10a17e000 -        0x10a1adfff sketchybar (*) <8d01eab3-1f02-3c1c-8a59-13fb6d9f0f6f> /usr/local/Cellar/sketchybar/HEAD-9d9529c/bin/sketchybar
    0x7ff81f178000 -     0x7ff81f671fff com.apple.MediaRemote (1.0) <13facb7b-f1f3-305b-815e-b45dd6f5d677> /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
    0x7ff807b5f000 -     0x7ff807ba5fff libdispatch.dylib (*) <1a04b380-76e4-3e4b-b0fc-9837533d021d> /usr/lib/system/libdispatch.dylib
    0x7ff807d60000 -     0x7ff808262fff com.apple.CoreFoundation (6.9) <93c48919-68af-367e-9a67-db4159bc962c> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff810a5f000 -     0x7ff810d52fff com.apple.HIToolbox (2.1.1) <06fdecd6-9f69-397b-b1e2-a8226c0ba7ed> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x11118d000 -        0x1111f8fff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
    0x7ff807d13000 -     0x7ff807d1efff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib
    0x7ff807cdb000 -     0x7ff807d12fff libsystem_kernel.dylib (*) <8cc28466-fd2f-3c80-9834-9525b7beac19> /usr/lib/system/libsystem_kernel.dylib
    0x7ff8107ff000 -     0x7ff810820fff com.apple.audio.caulk (1.0) <8e7b3d95-1d47-3f17-9512-c5fcc30792c2> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7ff80f5ba000 -     0x7ff80f60bfff com.apple.CoreVideo (1.8) <65321388-a44f-3c17-bb4f-ff1c629f4476> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=847.2M resident=0K(0%) swapped_out_or_unallocated=847.2M(100%)
Writable regions: Total=561.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=561.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
CG backing stores                 1872K       31 
ColorSync                           68K        3 
CoreGraphics                        12K        2 
IOKit                             7940K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           164.4M       19 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
ObjC additional data                15K        1 
STACK GUARD                       56.0M        6 
Stack                             10.5M        6 
VM_ALLOCATE                        256K       62 
__DATA                            16.2M      276 
__DATA_CONST                      12.9M      170 
__DATA_DIRTY                       600K      101 
__FONT_DATA                          4K        1 
__LINKEDIT                       645.4M        8 
__TEXT                           201.8M      293 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      242.0M       13 
shared memory                      800K       20 
===========                     =======  ======= 
TOTAL                              1.7G     1022 
TOTAL, minus reserved VM space     1.3G     1022 



-----------
Full Report
-----------

{"app_name":"sketchybar","timestamp":"2023-10-31 10:26:37.00 -0400","app_version":"","slice_uuid":"8d01eab3-1f02-3c1c-8a59-13fb6d9f0f6f","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"FFC9DB06-2176-4E82-B3BA-B47C0F19971D","name":"sketchybar"}
{
  "uptime" : 570000,
  "procLaunch" : "2023-10-31 10:26:36.7471 -0400",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro14,1",
  "procStartAbsTime" : 571615027020425,
  "coalitionID" : 67244,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-31 10:26:37.7842 -0400",
  "incident" : "FFC9DB06-2176-4E82-B3BA-B47C0F19971D",
  "bug_type" : "309",
  "pid" : 10787,
  "procExitAbsTime" : 571616056410049,
  "cpuType" : "X86-64",
  "procName" : "sketchybar",
  "procPath" : "\/usr\/local\/opt\/sketchybar\/bin\/sketchybar",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "homebrew.mxcl.sketchybar",
  "crashReporterKey" : "B945E6FE-3CE4-EB79-12B2-9BAF0A92AB40",
  "wakeTime" : 2170,
  "sleepWakeUUID" : "3E4A69A8-68AC-48BC-B31F-373E503E4646",
  "sip" : "enabled",
  "vmRegionInfo" : "0x180080020 is not in any region.  Bytes after previous region: 1671811105  Bytes before following region: 105546673291232\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 111245000-11c623000    [179.9M] r--\/rwx SM=COW  ...t_id=c48561b7\n--->  GAP OF 0x5ffee39dd000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000180080020","rawCodes":[1,6442975264],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000180080020"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":10787},
  "vmregioninfo" : "0x180080020 is not in any region.  Bytes after previous region: 1671811105  Bytes before following region: 105546673291232\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 111245000-11c623000    [179.9M] r--\/rwx SM=COW  ...t_id=c48561b7\n--->  GAP OF 0x5ffee39dd000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":6996722,"instructionState":{"instructionStream":{"bytes":[95,93,195,73,139,70,32,76,33,248,72,139,72,8,72,137,200,72,131,224,254,246,193,1,117,30,139,64,8,131,192,7,131,224,248,72,1,240,72,131,248,17,190,16,0,0,0,72,15,67,240,233,104,255,255,255,72,139,0,235,221,72,133,255,15,132,131,0,0,0,137,248,131,224,1,72,133,192,117,121,72,139,7,72,185,248,255,255,255,255,127,0,0,72,33,193,72,139,81,32,246,194,4,116,56,168,1,116,86,72,185,0,0,0,0,0,0,0,1,72,137,194,72,193,234,55,116,73,72,137,194,72,1,202,114,18,240,72,15,177,23,116,58,168,1,117,228,49,246,233,77,254,1,0,49,246,233,76,176,0,0,102,131,121,28,0,121,14,131,226,2,72,133,210,116,6,246,65,40,2,117,23,72,139,53,24,254,141,65,255,37,90],"offset":96}},"threadState":{"r13":{"value":140703258297344,"symbolLocation":0,"symbol":"objc_msgSend"},"rax":{"value":6442975232},"rflags":{"value":66054},"cpu":{"value":2},"r14":{"value":140629560566272},"rsi":{"value":140703708558637},"r8":{"value":11},"cr2":{"value":6442975264},"rdx":{"value":105553178934304},"r10":{"value":4464505618,"symbolLocation":2,"symbol":"OBJC_CLASS_$_media_context"},"r9":{"value":3},"r15":{"value":105553178938208},"rbx":{"value":105553172661632},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":4464478848,"symbolLocation":0,"symbol":"-[media_context setApp:]"},"rip":{"value":140703258296979,"matchesCrashFrame":1},"rbp":{"value":140701884483888},"rsp":{"value":140701884483832},"r12":{"value":0},"rcx":{"value":6442975232},"flavor":"x86_THREAD_STATE","rdi":{"value":105553178934304}},"queue":"com.apple.main-thread","frames":[{"imageOffset":25235,"symbol":"objc_retain","symbolLocation":35,"imageIndex":0},{"imageOffset":66899,"symbol":"objc_setProperty_atomic","symbolLocation":47,"imageIndex":0},{"imageOffset":174469,"symbol":"__30-[media_context media_change:]_block_invoke_2","symbolLocation":53,"imageIndex":1},{"imageOffset":2049838,"symbol":"__MRMediaRemoteGetNowPlayingInfoForOrigin_block_invoke","symbolLocation":78,"imageIndex":2},{"imageOffset":2049328,"symbol":"__MRMediaRemoteGetNowPlayingInfoForPlayer_block_invoke","symbolLocation":64,"imageIndex":2},{"imageOffset":2060880,"symbol":"___MRGetNowPlayingInfo_block_invoke_2","symbolLocation":48,"imageIndex":2},{"imageOffset":8396,"symbol":"_dispatch_call_block_and_release","symbolLocation":12,"imageIndex":3},{"imageOffset":13079,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":3},{"imageOffset":64632,"symbol":"_dispatch_main_queue_drain","symbolLocation":943,"imageIndex":3},{"imageOffset":63675,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":31,"imageIndex":3},{"imageOffset":778039,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":9,"imageIndex":4},{"imageOffset":520143,"symbol":"__CFRunLoopRun","symbolLocation":2771,"imageIndex":4},{"imageOffset":515644,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":4},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":5},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":5},{"imageOffset":1565418,"symbol":"_AcquireNextEvent","symbolLocation":45,"imageIndex":5},{"imageOffset":1535773,"symbol":"RunApplicationEventLoop","symbolLocation":174,"imageIndex":5},{"imageOffset":19790,"symbol":"main","symbolLocation":862,"imageIndex":1},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":6}]},{"id":6996723,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":6996725,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":6996805,"name":"AMCP Logging Spool","frames":[{"imageOffset":6582,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":8},{"imageOffset":107238,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":16,"imageIndex":9},{"imageOffset":8520,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":9},{"imageOffset":7692,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":41,"imageIndex":9},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":6997095,"name":"CVDisplayLink","frames":[{"imageOffset":17386,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":8},{"imageOffset":27300,"symbol":"_pthread_cond_wait","symbolLocation":1302,"imageIndex":7},{"imageOffset":11872,"symbol":"CVDisplayLink::waitUntil(unsigned long long)","symbolLocation":370,"imageIndex":10},{"imageOffset":7644,"symbol":"CVDisplayLink::runIOThread()","symbolLocation":526,"imageIndex":10},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":6997194,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703258271744,
    "size" : 237568,
    "uuid" : "4d9b0dca-7151-3875-b98e-b255db8267a8",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4464304128,
    "size" : 196608,
    "uuid" : "8d01eab3-1f02-3c1c-8a59-13fb6d9f0f6f",
    "path" : "\/usr\/local\/Cellar\/sketchybar\/HEAD-9d9529c\/bin\/sketchybar",
    "name" : "sketchybar"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703650250752,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.MediaRemote",
    "size" : 5218304,
    "uuid" : "13facb7b-f1f3-305b-815e-b45dd6f5d677",
    "path" : "\/System\/Library\/PrivateFrameworks\/MediaRemote.framework\/Versions\/A\/MediaRemote",
    "name" : "MediaRemote",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703257980928,
    "size" : 290816,
    "uuid" : "1a04b380-76e4-3e4b-b0fc-9837533d021d",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703260082176,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "93c48919-68af-367e-9a67-db4159bc962c",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703407927296,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "06fdecd6-9f69-397b-b1e2-a8226c0ba7ed",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4581806080,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703259766784,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703259537408,
    "size" : 229376,
    "uuid" : "8cc28466-fd2f-3c80-9834-9525b7beac19",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703405436928,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 139264,
    "uuid" : "8e7b3d95-1d47-3f17-9512-c5fcc30792c2",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703386279936,
    "CFBundleShortVersionString" : "1.8",
    "CFBundleIdentifier" : "com.apple.CoreVideo",
    "size" : 335872,
    "uuid" : "65321388-a44f-3c17-bb4f-ff1c629f4476",
    "path" : "\/System\/Library\/Frameworks\/CoreVideo.framework\/Versions\/A\/CoreVideo",
    "name" : "CoreVideo",
    "CFBundleVersion" : "480.1"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703256510464,
  "size" : 19331678208,
  "uuid" : "73669942-bd8a-3e40-951f-7fbe07b51cb8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=847.2M resident=0K(0%) swapped_out_or_unallocated=847.2M(100%)\nWritable regions: Total=561.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=561.1M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG backing stores                 1872K       31 \nColorSync                           68K        3 \nCoreGraphics                        12K        2 \nIOKit                             7940K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           164.4M       19 \nMALLOC guard page                   16K        4 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        6 \nStack                             10.5M        6 \nVM_ALLOCATE                        256K       62 \n__DATA                            16.2M      276 \n__DATA_CONST                      12.9M      170 \n__DATA_DIRTY                       600K      101 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       645.4M        8 \n__TEXT                           201.8M      293 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      242.0M       13 \nshared memory                      800K       20 \n===========                     =======  ======= \nTOTAL                              1.7G     1022 \nTOTAL, minus reserved VM space     1.3G     1022 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    }
  ],
  "experiments" : [

  ]
}
}


  }
  ```
</details>

**Comment by FelixKratz** [comment]
Thanks for posting the crash report, I think I will be able to fix this particular crash before the next release.

**Comment by bassamsdata** [comment]
I've been testing the `--head` version for 2 days, and it was working flawlessly, but with one issue.

from my observation, I noticed that when I open the brave browser and then open multiple video tabs (like multiple youtube video tabs and play them) the sketchybar goes crazy and keeps restarting, but I'm not sure if my observation is correct.

<details>
  <summary>new crash report</summary>
  
  ```report
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               sketchybar [59588]
Path:                  /usr/local/opt/sketchybar/bin/sketchybar
Identifier:            sketchybar
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-07 13:13:12.1316 -0500
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        B945E6FE-3CE4-EB79-12B2-9BAF0A92AB40

Sleep/Wake UUID:       8F0A174F-0FF1-43D6-8726-DBF9EB3BFBDA

Time Awake Since Boot: 67000 seconds
Time Since Wake:       6272 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000001a0080020
Exception Codes:       0x0000000000000001, 0x00000001a0080020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [59588]

VM Region Info: 0x1a0080020 is not in any region.  Bytes after previous region: 2407350305  Bytes before following region: 105546136420320
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      CG backing stores           110887000-1108ac000    [  148K] rw-/rw- SM=PRV  
--->  GAP OF 0x5ffeef754000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff815ffe293 objc_retain + 35
1   libobjc.A.dylib               	    0x7ff816008553 objc_setProperty_atomic + 47
2   sketchybar                    	       0x10097e965 __30-[media_context media_change:]_block_invoke_2 + 53
3   MediaRemote                   	    0x7ff82d7be72e __MRMediaRemoteGetNowPlayingInfoForOrigin_block_invoke + 78
4   MediaRemote                   	    0x7ff82d7be530 __MRMediaRemoteGetNowPlayingInfoForPlayer_block_invoke + 64
5   MediaRemote                   	    0x7ff82d7c1250 ___MRGetNowPlayingInfo_block_invoke_2 + 48
6   libdispatch.dylib             	    0x7ff815fb30cc _dispatch_call_block_and_release + 12
7   libdispatch.dylib             	    0x7ff815fb4317 _dispatch_client_callout + 8
8   libdispatch.dylib             	    0x7ff815fc0c78 _dispatch_main_queue_drain + 943
9   libdispatch.dylib             	    0x7ff815fc08bb _dispatch_main_queue_callback_4CF + 31
10  CoreFoundation                	    0x7ff81626ff37 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                	    0x7ff816230fcf __CFRunLoopRun + 2771
12  CoreFoundation                	    0x7ff81622fe3c CFRunLoopRunSpecific + 562
13  HIToolbox                     	    0x7ff81eedf5e6 RunCurrentEventLoopInMode + 292
14  HIToolbox                     	    0x7ff81eedf34a ReceiveNextEventCommon + 594
15  HIToolbox                     	    0x7ff81f02f2ea _AcquireNextEvent + 45
16  HIToolbox                     	    0x7ff81f027f1d RunApplicationEventLoop + 174
17  sketchybar                    	       0x100958cfe main + 862
18  dyld                          	       0x10391152e start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff816166f48 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff816166f48 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff816166f48 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff816166f48 start_wqthread + 0

Thread 5:: AMCP Logging Spool
0   libsystem_kernel.dylib        	    0x7ff81612e9b6 semaphore_wait_trap + 10
1   caulk                         	    0x7ff81ec6b2e6 caulk::mach::semaphore::wait_or_error() + 16
2   caulk                         	    0x7ff81ec53148 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	    0x7ff81ec52e0c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81616b4e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff816166f6b thread_start + 15

Thread 6:: CVDisplayLink
0   libsystem_kernel.dylib        	    0x7ff8161313ea __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81616baa4 _pthread_cond_wait + 1302
2   CoreVideo                     	    0x7ff81da0ee60 CVDisplayLink::waitUntil(unsigned long long) + 370
3   CoreVideo                     	    0x7ff81da0dddc CVDisplayLink::runIOThread() + 526
4   libsystem_pthread.dylib       	    0x7ff81616b4e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff816166f6b thread_start + 15


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000001a0080001  rbx: 0x000060000219d6f0  rcx: 0x00000001a0080000  rdx: 0x0000600002f867a0
  rdi: 0x0000600002f867a0  rsi: 0x00007ff830d6552d  rbp: 0x00007ff7bf5aa930  rsp: 0x00007ff7bf5aa8f8
   r8: 0x000000000000000b   r9: 0x0000000000000003  r10: 0x0000000100985332  r11: 0x000000010097ea60
  r12: 0x0000000000000000  r13: 0x00007ff815ffe400  r14: 0x00007fbeed80d200  r15: 0x0000600002f86c00
  rip: 0x00007ff815ffe293  rfl: 0x0000000000010206  cr2: 0x00000001a0080020
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  5f 5d c3 49 8b 46 20 4c-21 f8 48 8b 48 08 48 89  _].I.F L!.H.H.H.
  c8 48 83 e0 fe f6 c1 01-75 1e 8b 40 08 83 c0 07  .H......u..@....
  83 e0 f8 48 01 f0 48 83-f8 11 be 10 00 00 00 48  ...H..H........H
  0f 43 f0 e9 68 ff ff ff-48 8b 00 eb dd 48 85 ff  .C..h...H....H..
  0f 84 83 00 00 00 89 f8-83 e0 01 48 85 c0 75 79  ...........H..uy
  48 8b 07 48 b9 f8 ff ff-ff ff 7f 00 00 48 21 c1  H..H.........H!.
 [48]8b 51 20 f6 c2 04 74-38 a8 01 74 56 48 b9 00  H.Q ...t8..tVH..	<==
  00 00 00 00 00 00 01 48-89 c2 48 c1 ea 37 74 49  .......H..H..7tI
  48 89 c2 48 01 ca 72 12-f0 48 0f b1 17 74 3a a8  H..H..r..H...t:.
  01 75 e4 31 f6 e9 4d fe-01 00 31 f6 e9 4c b0 00  .u.1..M...1..L..
  00 66 83 79 1c 00 79 0e-83 e2 02 48 85 d2 74 06  .f.y..y....H..t.
  f6 41 28 02 75 17 48 8b-35 18 fe 8d 41 ff 25 5a  .A(.u.H.5...A.%Z

Binary Images:
    0x7ff815ff8000 -     0x7ff816031fff libobjc.A.dylib (*) <4d9b0dca-7151-3875-b98e-b255db8267a8> /usr/lib/libobjc.A.dylib
       0x100954000 -        0x100983fff sketchybar (*) <39d5b6a0-b096-36e9-9c8a-676fca9c4ca6> /usr/local/Cellar/sketchybar/HEAD-af6c7fc/bin/sketchybar
    0x7ff82d5ca000 -     0x7ff82dac3fff com.apple.MediaRemote (1.0) <13facb7b-f1f3-305b-815e-b45dd6f5d677> /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
    0x7ff815fb1000 -     0x7ff815ff7fff libdispatch.dylib (*) <1a04b380-76e4-3e4b-b0fc-9837533d021d> /usr/lib/system/libdispatch.dylib
    0x7ff8161b2000 -     0x7ff8166b4fff com.apple.CoreFoundation (6.9) <93c48919-68af-367e-9a67-db4159bc962c> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81eeb1000 -     0x7ff81f1a4fff com.apple.HIToolbox (2.1.1) <06fdecd6-9f69-397b-b1e2-a8226c0ba7ed> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x10390c000 -        0x103977fff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
    0x7ff816165000 -     0x7ff816170fff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib
    0x7ff81612d000 -     0x7ff816164fff libsystem_kernel.dylib (*) <8cc28466-fd2f-3c80-9834-9525b7beac19> /usr/lib/system/libsystem_kernel.dylib
    0x7ff81ec51000 -     0x7ff81ec72fff com.apple.audio.caulk (1.0) <8e7b3d95-1d47-3f17-9512-c5fcc30792c2> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7ff81da0c000 -     0x7ff81da5dfff com.apple.CoreVideo (1.8) <65321388-a44f-3c17-bb4f-ff1c629f4476> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=847.2M resident=0K(0%) swapped_out_or_unallocated=847.2M(100%)
Writable regions: Total=561.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=561.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
CG backing stores                 1948K       31 
ColorSync                           68K        3 
CoreGraphics                        12K        2 
IOKit                             7940K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           164.4M       19 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
ObjC additional data                15K        1 
STACK GUARD                       56.0M        7 
Stack                             11.0M        7 
VM_ALLOCATE                        224K       54 
__DATA                            16.2M      275 
__DATA_CONST                      12.9M      172 
__DATA_DIRTY                       600K      101 
__FONT_DATA                          4K        1 
__LINKEDIT                       645.4M        8 
__TEXT                           201.8M      293 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      241.8M       12 
shared memory                      832K       25 
===========                     =======  ======= 
TOTAL                              1.7G     1021 
TOTAL, minus reserved VM space     1.3G     1021 



-----------
Full Report
-----------

{"app_name":"sketchybar","timestamp":"2023-11-07 13:13:12.00 -0500","app_version":"","slice_uuid":"39d5b6a0-b096-36e9-9c8a-676fca9c4ca6","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"D43695B4-37EA-42F5-A41E-94497DAAEF6A","name":"sketchybar"}
{
  "uptime" : 67000,
  "procLaunch" : "2023-11-07 13:13:10.0153 -0500",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro14,1",
  "procStartAbsTime" : 67550216524435,
  "coalitionID" : 8585,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-07 13:13:12.1316 -0500",
  "incident" : "D43695B4-37EA-42F5-A41E-94497DAAEF6A",
  "bug_type" : "309",
  "pid" : 59588,
  "procExitAbsTime" : 67552317629277,
  "cpuType" : "X86-64",
  "procName" : "sketchybar",
  "procPath" : "\/usr\/local\/opt\/sketchybar\/bin\/sketchybar",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "homebrew.mxcl.sketchybar",
  "crashReporterKey" : "B945E6FE-3CE4-EB79-12B2-9BAF0A92AB40",
  "wakeTime" : 6272,
  "sleepWakeUUID" : "8F0A174F-0FF1-43D6-8726-DBF9EB3BFBDA",
  "sip" : "enabled",
  "vmRegionInfo" : "0x1a0080020 is not in any region.  Bytes after previous region: 2407350305  Bytes before following region: 105546136420320\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CG backing stores           110887000-1108ac000    [  148K] rw-\/rw- SM=PRV  \n--->  GAP OF 0x5ffeef754000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001a0080020","rawCodes":[1,6979846176],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000001a0080020"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":59588},
  "vmregioninfo" : "0x1a0080020 is not in any region.  Bytes after previous region: 2407350305  Bytes before following region: 105546136420320\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CG backing stores           110887000-1108ac000    [  148K] rw-\/rw- SM=PRV  \n--->  GAP OF 0x5ffeef754000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":851008,"instructionState":{"instructionStream":{"bytes":[95,93,195,73,139,70,32,76,33,248,72,139,72,8,72,137,200,72,131,224,254,246,193,1,117,30,139,64,8,131,192,7,131,224,248,72,1,240,72,131,248,17,190,16,0,0,0,72,15,67,240,233,104,255,255,255,72,139,0,235,221,72,133,255,15,132,131,0,0,0,137,248,131,224,1,72,133,192,117,121,72,139,7,72,185,248,255,255,255,255,127,0,0,72,33,193,72,139,81,32,246,194,4,116,56,168,1,116,86,72,185,0,0,0,0,0,0,0,1,72,137,194,72,193,234,55,116,73,72,137,194,72,1,202,114,18,240,72,15,177,23,116,58,168,1,117,228,49,246,233,77,254,1,0,49,246,233,76,176,0,0,102,131,121,28,0,121,14,131,226,2,72,133,210,116,6,246,65,40,2,117,23,72,139,53,24,254,141,65,255,37,90],"offset":96}},"threadState":{"r13":{"value":140703497708544,"symbolLocation":0,"symbol":"objc_msgSend"},"rax":{"value":6979846145},"rflags":{"value":66054},"cpu":{"value":2},"r14":{"value":140458005156352},"rsi":{"value":140703947969837},"r8":{"value":11},"cr2":{"value":6979846176},"rdx":{"value":105553166100384},"r10":{"value":4304950066,"symbolLocation":2,"symbol":"OBJC_CLASS_$_media_context"},"r9":{"value":3},"r15":{"value":105553166101504},"rbx":{"value":105553151514352},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":4304923232,"symbolLocation":0,"symbol":"-[media_context setApp:]"},"rip":{"value":140703497708179,"matchesCrashFrame":1},"rbp":{"value":140702044039472},"rsp":{"value":140702044039416},"r12":{"value":0},"rcx":{"value":6979846144},"flavor":"x86_THREAD_STATE","rdi":{"value":105553166100384}},"queue":"com.apple.main-thread","frames":[{"imageOffset":25235,"symbol":"objc_retain","symbolLocation":35,"imageIndex":0},{"imageOffset":66899,"symbol":"objc_setProperty_atomic","symbolLocation":47,"imageIndex":0},{"imageOffset":174437,"symbol":"__30-[media_context media_change:]_block_invoke_2","symbolLocation":53,"imageIndex":1},{"imageOffset":2049838,"symbol":"__MRMediaRemoteGetNowPlayingInfoForOrigin_block_invoke","symbolLocation":78,"imageIndex":2},{"imageOffset":2049328,"symbol":"__MRMediaRemoteGetNowPlayingInfoForPlayer_block_invoke","symbolLocation":64,"imageIndex":2},{"imageOffset":2060880,"symbol":"___MRGetNowPlayingInfo_block_invoke_2","symbolLocation":48,"imageIndex":2},{"imageOffset":8396,"symbol":"_dispatch_call_block_and_release","symbolLocation":12,"imageIndex":3},{"imageOffset":13079,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":3},{"imageOffset":64632,"symbol":"_dispatch_main_queue_drain","symbolLocation":943,"imageIndex":3},{"imageOffset":63675,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":31,"imageIndex":3},{"imageOffset":778039,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":9,"imageIndex":4},{"imageOffset":520143,"symbol":"__CFRunLoopRun","symbolLocation":2771,"imageIndex":4},{"imageOffset":515644,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":4},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":5},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":5},{"imageOffset":1565418,"symbol":"_AcquireNextEvent","symbolLocation":45,"imageIndex":5},{"imageOffset":1535773,"symbol":"RunApplicationEventLoop","symbolLocation":174,"imageIndex":5},{"imageOffset":19710,"symbol":"main","symbolLocation":862,"imageIndex":1},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":6}]},{"id":851011,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":851012,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":851036,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":851037,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":851148,"name":"AMCP Logging Spool","frames":[{"imageOffset":6582,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":8},{"imageOffset":107238,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":16,"imageIndex":9},{"imageOffset":8520,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":9},{"imageOffset":7692,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":41,"imageIndex":9},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":851474,"name":"CVDisplayLink","frames":[{"imageOffset":17386,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":8},{"imageOffset":27300,"symbol":"_pthread_cond_wait","symbolLocation":1302,"imageIndex":7},{"imageOffset":11872,"symbol":"CVDisplayLink::waitUntil(unsigned long long)","symbolLocation":370,"imageIndex":10},{"imageOffset":7644,"symbol":"CVDisplayLink::runIOThread()","symbolLocation":526,"imageIndex":10},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703497682944,
    "size" : 237568,
    "uuid" : "4d9b0dca-7151-3875-b98e-b255db8267a8",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4304748544,
    "size" : 196608,
    "uuid" : "39d5b6a0-b096-36e9-9c8a-676fca9c4ca6",
    "path" : "\/usr\/local\/Cellar\/sketchybar\/HEAD-af6c7fc\/bin\/sketchybar",
    "name" : "sketchybar"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703889661952,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.MediaRemote",
    "size" : 5218304,
    "uuid" : "13facb7b-f1f3-305b-815e-b45dd6f5d677",
    "path" : "\/System\/Library\/PrivateFrameworks\/MediaRemote.framework\/Versions\/A\/MediaRemote",
    "name" : "MediaRemote",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703497392128,
    "size" : 290816,
    "uuid" : "1a04b380-76e4-3e4b-b0fc-9837533d021d",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703499493376,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "93c48919-68af-367e-9a67-db4159bc962c",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703647338496,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "06fdecd6-9f69-397b-b1e2-a8226c0ba7ed",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4354785280,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703499177984,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703498948608,
    "size" : 229376,
    "uuid" : "8cc28466-fd2f-3c80-9834-9525b7beac19",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703644848128,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 139264,
    "uuid" : "8e7b3d95-1d47-3f17-9512-c5fcc30792c2",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703625691136,
    "CFBundleShortVersionString" : "1.8",
    "CFBundleIdentifier" : "com.apple.CoreVideo",
    "size" : 335872,
    "uuid" : "65321388-a44f-3c17-bb4f-ff1c629f4476",
    "path" : "\/System\/Library\/Frameworks\/CoreVideo.framework\/Versions\/A\/CoreVideo",
    "name" : "CoreVideo",
    "CFBundleVersion" : "480.1"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703495921664,
  "size" : 19331678208,
  "uuid" : "73669942-bd8a-3e40-951f-7fbe07b51cb8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=847.2M resident=0K(0%) swapped_out_or_unallocated=847.2M(100%)\nWritable regions: Total=561.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=561.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG backing stores                 1948K       31 \nColorSync                           68K        3 \nCoreGraphics                        12K        2 \nIOKit                             7940K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           164.4M       19 \nMALLOC guard page                   16K        4 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        7 \nStack                             11.0M        7 \nVM_ALLOCATE                        224K       54 \n__DATA                            16.2M      275 \n__DATA_CONST                      12.9M      172 \n__DATA_DIRTY                       600K      101 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       645.4M        8 \n__TEXT                           201.8M      293 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      241.8M       12 \nshared memory                      832K       25 \n===========                     =======  ======= \nTOTAL                              1.7G     1021 \nTOTAL, minus reserved VM space     1.3G     1021 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    }
  ],
  "experiments" : [

  ]
}
}

  ```
</details>

**Comment by FelixKratz** [comment]
Yes I think your observation is correct, the crash happens in the media_change event handler when trying to retain a value. Will look into fixing this problem.

**Comment by bassamsdata** [comment]
thank you so much for your responses and help. i've been testing the newest version, Sketchybar v2.19.01, and it works perfectly with no issues—except for one involving media. the problem arises with chrome and brave browsers. 
any playing video on these browsers triggers the issue. 

However, i won't reopen this issue for two reasons: firstly, the problem doesn't occur on Firefox or Arc (although this browser is built on chromium), and secondly, i primarily use arc nowadays, so i haven't experienced the issue.

thanks again!

**Comment by FelixKratz** [comment]
I have just release 2.19.2 and I hope these problems are now finally solved.

**Comment by thebiblelover7** [comment]
Hmm, I'm on version 2.19.5 and I still have the same problem... I can reproduce it so easily, closing the lid and then reopening within a couple seconds makes sketchybar disappear. It's still running (according to Activity Monitor), but it's not visible at all...

**Comment by BrandonShega** [comment]
I installed this maybe a week ago and I'm also experiencing this :( Was there ever a fix for it?

**Comment by FelixKratz** [comment]
I am not totally sure that it did the trick, but after this commit: https://github.com/FelixKratz/SketchyBar/commit/a3a84ecf956e33a342e8bfce0534c66f38829dad I didnt see the problem occuring anymore.
