### ISSUE TITLE
Sketchybar sometimes stops updating when system wakes from sleep

### ISSUE THREAD

**Issue by SxC97** [FelixKratz/SketchyBar#97]
I have a clock plugin that updates once per second and sometimes when the machine is awakened from sleep, the clock module no longer updates. This is not unique to the clock plugin but it is the most noticeable example.

Manually running `sketchybar -m —refresh` in a terminal does not fix the issue either.

I have managed to find a work around by adding `yabai -m signal --add event=system_woke action="brew services restart sketchybar"` to the end of my `.yabairc` file.

**Comment by FelixKratz** [comment]
I will investigate but have not noticed that myself. Did you mean `sketchybar -m --update`? I might load in your config over night and see if it happens to me as well. What you could also check is when nothing updates anymore see in Activity Monitor how many `sketchybar` instances are running. This could be caused by the forks not being timed out. So if some script does not terminate while in sleep mode there will be too many forks, limiting the ability to spawn new forks #71.

**Comment by SxC97** [comment]
Sorry for the confusion, I did mean `sketchybar -m --update `. I have removed my work around from my `.yabairc` and will keep an eye on Activity Monitor to see how many forks exist. 

I have noticed some odd behavior from sketchybar inbetween waking from sleep and the `brew services restart sketchybar` command being run from yabai. Sometimes the clock will jump forward several seconds at a time until the service is restarted, then the clock updates 1 second at a time as expected. This might also be related to the fork timeout issue mentioned in #71.

**Comment by SxC97** [comment]
Ok, so this doesn’t happen every time but I did manage to recreate it today. I took some screenshots of activity monitor and it looks like theres only one sketchybar process with multiple threads running. Perhaps these screenshots could be of more use? I had to take them relatively quickly incase the bar started behaving normally again, so they look a little messy.

<img width="1680" alt="Screen Shot 2021-11-04 at T16 08 38" src="https://user-images.githubusercontent.com/53032923/140420682-b5ff38e3-f9ff-40db-bb6c-18402aedd5da.png">
<img width="1680" alt="Screen Shot 2021-11-04 at T16 08 50" src="https://user-images.githubusercontent.com/53032923/140420684-eaf250f2-8ab1-4fba-81af-6a44e063e307.png">
<img width="1680" alt="Screen Shot 2021-11-04 at T16 08 57" src="https://user-images.githubusercontent.com/53032923/140420685-1a0f4e75-fa66-4a23-a61a-5cb7fe5cd40f.png">
<img width="1680" alt="Screen Shot 2021-11-04 at T16 09 03" src="https://user-images.githubusercontent.com/53032923/140420688-208014bf-d08b-4a54-932b-90dc59acea33.png">

**Comment by FelixKratz** [comment]
I believe I have an idea: You have set updates=when_shown for all items. If your system enters sleep it will disconnect all displays. If the render loop is run once more after that, all items are set to *not* shown because there is no display -> no item will update anymore -> the bar is frozen, explaining the 0.0 cpu percent. You could try to validate this theory by setting updates=on for the clock exclusively, if I am correct in my assumption this should fix the freezes.

**Comment by SxC97** [comment]
Ah, good idea! I’ve set `updates=on` for the clock plugin. I will report back if this fixes the issue.

**Comment by FelixKratz** [comment]
Maybe this c24a682794380c003206610ffb024bd6d4a4b030 will fix this bug.

**Comment by SxC97** [comment]
Reporting back after setting `updates=on` for the clock module and updating to v2.2.0. Looks like the bar still freezes when waking from sleep. I have some more screenshots of activity monitor if that helps at all.

<img width="1680" alt="Screen Shot 2021-11-07 at T09 54 29" src="https://user-images.githubusercontent.com/53032923/140658170-f68d57df-e80a-4982-a624-b8ffa393332d.png">
<img width="1680" alt="Screen Shot 2021-11-07 at T09 54 37" src="https://user-images.githubusercontent.com/53032923/140658174-d9b43124-6e01-4e3b-a32e-22bbb05e982a.png">


How can I test c24a682 without it being a release?

**Comment by FelixKratz** [comment]
If you are using brew you can simply:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install --HEAD sketchybar
brew services start sketchybar
```
*BUT* then you are on a specific commit and you will not receive updates from brew update, so make sure to go back to the stable version after testing with:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar
brew services start sketchybar
```

**Comment by SxC97** [comment]
ok, cool! I’ve installed c24a682 and will report back if this fixes the issue.

**Comment by FelixKratz** [comment]
Any news on this?

**Comment by SxC97** [comment]
Looks like the freezing issue still exists. It’s much more rare than before. Now, the bar seems to completely freeze and when mousing over the bar, I get a spinning beach ball. 
<img width="1680" alt="Screen Shot 2021-11-11 at T10 31 09" src="https://user-images.githubusercontent.com/53032923/141334277-967edf20-8371-4157-9564-990a2d796484.png">

There is another issue that seems to have become more common with c24a682. After waking, the bar seems to update some elements several times per second. This might have to do with the threads all being delayed in favor of some other system threads, then all being resolved at once.

I have been trying to capture a screen recording of this behavior (thats whats taken so long to reply) but my computer is simply too slow. By the time I get the screen recording utility up, the bar has already gone back to normal. Perhaps this is not an issue on machines with more cores or better per thread performance?

**Comment by SxC97** [comment]
I *finally* managed to get a screen recording of the flickering issue!

https://user-images.githubusercontent.com/53032923/141602133-aaccd64f-9809-452d-b347-860c82107949.mov

**Comment by FelixKratz** [comment]
I believe this c648823b9eca9d2ae22e8d163ff374da0ce0c19a should finally fix it. Can you give it a try and report back?

**Comment by SxC97** [comment]
Sure thing!

**Comment by SxC97** [comment]
Back from testing, c648823 seems to have *completely* fixed the problem! I will close the issue for now and reopen if I notice it happening again.

**Comment by SxC97** [comment]
Whoops, looks like the issue is back 😭. I let my machine go to sleep and left it for ~3 hours and all of a sudden the bar froze when I woke the system. Maybe previous times I let the machine go to sleep, I woke it up too quickly. This time, I left the system asleep for ~3+ hours before waking it up and the bug seems to be back, albeit less frequently than before.

<img width="1680" alt="Screen Shot 2021-11-14 at T16 43 36" src="https://user-images.githubusercontent.com/53032923/141701777-d2affa9c-657a-44b0-b7e6-87a389eeb114.png">

The bar also beach balls my cursor, but I was not able to capture that with the screenshot utility.

<img width="1680" alt="Screen Shot 2021-11-14 at T16 51 13" src="https://user-images.githubusercontent.com/53032923/141701850-d66f31d3-b20e-4301-93cd-cbc31e8d1f64.png">
<img width="1680" alt="Screen Shot 2021-11-14 at T16 51 18" src="https://user-images.githubusercontent.com/53032923/141701852-8e67e40a-996a-4f7e-b809-877aa05afe7b.png">
<img width="1680" alt="Screen Shot 2021-11-14 at T16 51 22" src="https://user-images.githubusercontent.com/53032923/141701854-d66ba237-484d-49b6-9717-8ea6f1167bb9.png">

I also noticed that it was frozen in Activity Monitor, so I took some screenshots and took a sample that might be useful in debugging.

[Sample of sketchybar.txt](https://github.com/FelixKratz/SketchyBar/files/7534858/Sample.of.sketchybar.txt)

**Comment by FelixKratz** [comment]
I will think about this some more, but I am starting to run out of ideas, especially since I can not reproduce the behavior.

**Comment by SxC97** [comment]
Seeing as I am the only one commenting in this thread, this issue might be unique to my setup. There might be another program causing sketchybar to hang or some other part of my config that conflicts with sketchybar. Either way, the bar hangs far less frequently than before and the flickering issue also appears to be fixed, so I can certainly call that a win!

**Comment by FelixKratz** [comment]
I am sure we will find the problem, I will have some time on the weekend and I will try to drive your setup for some time (is it still the same that you have posted to the discussion?) maybe I can see what is going on and I will look into the sample you posted. Even if it is a configuration „problem“ I ideally want that sketchybar never hangs or dies unexpectedly. I will also make sure to let my macbook sleep for some extended periods between testing

**Comment by FelixKratz** [comment]
This happened to me a few times now as well, I was not able to reconstruct why exactly this happens, but what is interesting is that the app seems to be running still in the background, just the application run loop is stuck. This can be observed by hooking onto the stuck application with a profiler. So for some reason the main thread application run loop hangs on some condition. I wonder if it may be connected to the use of `vfork`.

**Comment by FelixKratz** [comment]
This hasn't happened to me since I updated the client server code on the HEAD version to use the CLOEXEC flag for the file descriptor of the socket.
